version: "3.9"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    volumes:
      - /home/sysop/dns/whitelists/:/app/whitelists/
      - /home/sysop/dns/blacklists/:/app/blacklists/
      - /home/sysop/dns/logs/:/app/logs/
      - /home/sysop/dns/config.yml:/app/config.yml
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host
    restart: always
    volumes:
      - /home/sysop/dns/prometheus/:/etc/prometheus/:Z
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
volumes:
  prom_data:
