version: "2.1"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    #environment:
      #- TZ=Europe/Berlin # Optional to synchronize the log timestamp with host
    volumes:
      - ./blocky/config.yaml:/app/config.yml
      - ./blocky/blacklists:/app/blacklists/
      - ./blocky/whitelists:/app/whitelists/
      - ./blocky/logs:/app/logs/
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./blocky/prometheus/:/etc/prometheus/
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
volumes:
  prom_data:
